### PR TITLE
Dynalloc: Removed MAX_PROP_TABLE_SIZE, MAX_INDIV_PROP_TABLE_SIZE

### PR DESCRIPTION
**Pull request by erkyrath**
The `properties_table` and `individuals_table` arrays are now memlists.

There were some places in objects.c where we set a temporary pointer `p` to refer to `properties_table` or `individuals_table`. This got confusing when the array is realloced, so I've dropped the temporary pointer. This makes a few lines of code longer. Sorry.

Also in this PR:

The `routine_name` global (in asm.c, used to keep track of the routine name being compiled) is now a memlist (rather than being malloced every time).

The `sub_buffer` variable is removed from text.c. It was being set (in optimise_abbreviations) but never used for anything.

The "Completed in N seconds" line (generated by `-s`) is now a decimal instead of an integer number of seconds. It tries to show 3 significant figures. (Previously, on modern machines, it usually just said "0 seconds", which was not informative.) 

The value is computed from `gettimeofday()` and passed to `rennab()` as a float. If your platform does not support `gettimeofday()` (which would be pretty darn ancient, but let's not make assumptions) then you can add `#define NO_GETTIMEOFDAY_AVAILABLE` to the header to go back to integer seconds.

### CODE REVIEW

**Comment by DavidKinder** [comment]
I'm not so keen on the use of gettimeofday(), it's a BSD-ism and is deprecated in POSIX (since 2008, I think). But the POSIX clock_gettime() is even less well supported ... Does the Mac have timespec_get() from C11? If it does we could use that with a preprocessor test for C11.

**Comment by erkyrath** [comment]
MacOS has both of those. I suspect that both will be available on modern Unixes, but it sounds like timespec_get() has been deployed for longer. (clock_gettime() has a note "first appeared in Mac OSX 10.12", e.g. 2016.)

I'll update this to use timespec_get(); thanks. I should also take a look at this on my other half-zillion projects that use gettimeofday().

**Comment by erkyrath** [comment]
Actually, it sounds like timespec_get() only showed up in 2019... Well, it's not a big deal if medium-old machines miss out on this feature.

**Comment by erkyrath** [comment]
Updated PR. Turns out we use time-measurement in two places -- the optimise_pass() call does it too. So, what the heck, I factored time-measurement out into macros. See header.h.

It uses timespec_get() if C11, otherwise it tries using clock_gettime(). You can #define USE_OLD_TIME_API to go back to time(0). 

I thought about adding another macro for gettimeofday(), but eh, overthinking. I can add it if anybody asks.

**Comment by Kroc** [comment]
Thank you for providing the option to use the old time API, this was required to continue compiling on MSVC6/EPOC32!

**Pull request merged**
